### ISSUE TITLE
[Bug]: v0.217 doesnt properly migrate older schematisations

### ISSUE THREAD

**Issue by wvangerwen** [nens/threedi-schema#29]
### Contact Details

w.vangerwen@hhnk.nl

### Complexity

easy

### Priority

low prio

### What happened?

Migrating pretty old sqlites doesnt work anymore in one go, we need to migrate twice before the schematisation is properly migrated. Seems to be an issue since v0.217, when we used v0.216 this still worked properly. 

The first migration it will add version: None to the schema instead of 217.

### How to Reproduce?

download this old  [sqlite](https://github.com/threedi/hhnk-threedi-tools/blob/dbce6ba965cd26b945568a845122e2b51ac791ff/tests/data/model_test/bwn_test_pre_migration.sqlite) version 173.
in MI 3.28; processing/3Di/Schematisation/Migrate Spatialite

1st time raises error; version=None
2nd time it works.

tested on windows.

### What did you expect and what was the actual result?

migrated sqlite.

### Add screenshots, video's etc

-

### Relevant log output

```shell
QGIS version: 3.28.5-Firenze
QGIS code revision: 50adba36f2
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.6.3
GEOS version: 3.11.2-CAPI-1.17.2
PROJ version: Rel. 9.2.0, March 1st, 2023
PDAL version: 2.5.2 (git-version: 57c4e7)
Algorithm started at: 2023-07-07T16:05:13
Algorithm 'Migrate Spatialite' starting…
Input parameters:
{ 'INPUT' : 'C:\\Users\\wvangerwen\\Downloads\\bwn_test_pre_migration.sqlite' }

Traceback (most recent call last):
File "C:\Users\wvangerwen\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\ThreeDiToolbox\processing\schematisation_algorithms.py", line 77, in processAlgorithm
schema.validate_schema()
File "C:\Users\wvangerwen\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\ThreeDiToolbox\deps\threedi_schema\application\schema.py", line 145, in validate_schema
raise MigrationMissingError(
threedi_schema.application.errors.MigrationMissingError: This tool requires at least schema version 217. Current version: 173.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\wvangerwen\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\ThreeDiToolbox\processing\schematisation_algorithms.py", line 82, in processAlgorithm
schema.set_spatial_indexes()
File "C:\Users\wvangerwen\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\ThreeDiToolbox\deps\threedi_schema\application\schema.py", line 177, in set_spatial_indexes
raise MigrationMissingError(
threedi_schema.application.errors.MigrationMissingError: Setting views requires schema version 217. Current version: None.

Execution failed after 4.42 seconds

Loading resulting layers
Algorithm 'Migrate Spatialite' finished
QGIS version: 3.28.5-Firenze
QGIS code revision: 50adba36f2
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.6.3
GEOS version: 3.11.2-CAPI-1.17.2
PROJ version: Rel. 9.2.0, March 1st, 2023
PDAL version: 2.5.2 (git-version: 57c4e7)
Algorithm started at: 2023-07-07T16:06:49
Algorithm 'Migrate Spatialite' starting…
Input parameters:
{ 'INPUT' : 'C:\\Users\\wvangerwen\\Downloads\\bwn_test_pre_migration.sqlite' }

Execution completed in 1.53 seconds
Results:
{'OUTPUT': True}

Loading resulting layers
Algorithm 'Migrate Spatialite' finished
```

**Comment by leendertvanwolfswinkel** [comment]
Tested and in current MI version the provided spatialite migrates just fine
